<?php

/**
 * Developer Name : Alok Singh Narwaria
 * Created date	: 4 Jan 2015
 * 
 * This Module is developed for coursera to get services using curl and show the listing of courses.
 *   
 */

 /**
 * Implements hook_menu().
 */
function coursera_menu() {
$items['coursera/listing'] = array(
    'title' => 'Courses',
    'page callback' => 'coursera_list',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'coursera.inc',
  );
$items['coursera/courser/%'] = array(
    'title' => 'Courses full details',
    'page callback' => 'coursera_details',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'coursera.inc',
);
return $items;
}


 /**
  * Implements hook_theme().
  * Theme the content display for mobile compatible. 
  */
function coursera_theme($existing, $type, $theme, $path){
    return array(
            'courses_list_data'=>array(
                'template'=>'course-list-data',
                'path'=>$path.'/templates',
                'type'=>'theme',
                'variables' => array(
                    'coursesListArray' => NULL,                      
                ),
            ),  
            'courses_output_html'=>array(
                'template'=>'courses-output-html',
                'path'=>$path.'/templates',
                'type'=>'theme',
                'variables' => array(
                    'courseListHtml' => NULL,                      
                    'searchCourseFormHtml' => NULL,                      
                ),
            ),              
            'search_course_form'=>array(
            'template'=>'search-course-form',
            'path'=>$path.'/templates',
            'type'=>'theme',
            'variables' => array(
                'courseType' => NULL,
                'languages' => NULL,
                'certificates' => NULL,
                'categories' => NULL,
                'partnerIds' => NULL,
            ),
           ),      
            'course_detail_page'=>array(
            'template'=>'course-detail-page',
            'path'=>$path.'/templates',
            'type'=>'theme',
            'variables' => array(
                'elements' => NULL,
                'linked' => NULL,
                'languages' => NULL,
                'certificates' => NULL,
                'categories' => NULL,
                'partnerIds' => NULL,
            ),
        ),
    );
}

/*
 * Code Refernce 
 * URL : http://php.net/manual/en/function.sort.php 
 */
function array_sort($array, $on, $order=SORT_ASC){
    $new_array = array();
    $sortable_array = array();
    if (count($array) > 0) {
        foreach ($array as $k => $v) {
            if (is_array($v)) {
                foreach ($v as $k2 => $v2) {
                    if ($k2 == $on) {
                        $sortable_array[$k] = $v2;
                    }
                }
            } else {
                $sortable_array[$k] = $v;
            }
        }

        switch ($order) {
            case SORT_ASC:
                asort($sortable_array);
            break;
            case SORT_DESC:
                arsort($sortable_array);
            break;
        }

        foreach ($sortable_array as $k => $v) {
            $new_array[$k] = $array[$k];
        }
    }

    return $new_array;
}
?>
