<?php

/**
 * @file
 * Provides testing functionality.
 */
/**
 * Implements hook_help().
 */
function coursera_help($path, $arg) {
  switch ($path) {
    case 'admin/coursera#coursera':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Testing module provides a framework for running automated unit tests. It can be used to verify a working state of Drupal before and after any code changes, or as a means for developers to write and execute tests for their modules. For more information, see the online handbook entry for <a href="@simpletest">Testing module</a>.', array('@simpletest' => 'http://drupal.org/documentation/modules/simpletest', '@blocks' => url('admin/structure/block'))) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Running tests') . '</dt>';
      $output .= '<dd>' . t('Visit the <a href="@admin-simpletest">Testing page</a> to display a list of available tests. For comprehensive testing, select <em>all</em> tests, or individually select tests for more targeted testing. Note that it might take several minutes for all tests to complete. For more information on creating and modifying your own tests, see the <a href="@simpletest-api">Testing API Documentation</a> in the Drupal handbook.', array('@simpletest-api' => 'http://drupal.org/simpletest', '@admin-simpletest' => url('admin/config/development/testing'))) . '</dd>';
      $output .= '<dd>' . t('After the tests run, a message will be displayed next to each test group indicating whether tests within it passed, failed, or had exceptions. A pass means that the test returned the expected results, while fail means that it did not. An exception normally indicates an error outside of the test, such as a PHP warning or notice. If there were failures or exceptions, the results will be expanded to show details, and the tests that had failures or exceptions will be indicated in red or pink rows. You can then use these results to refine your code and tests, until all tests pass.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}   
 /**
 * Implements hook_menu().
 */
function coursera_menu() {
$items['coursera/listing'] = array(
    'title' => 'Courses',
    'page callback' => 'coursera_list',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'coursera.inc',
  );
$items['coursera/courser/%'] = array(
    'title' => 'Courses full details',
    'page callback' => 'coursera_details',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'coursera.inc',
  );
return $items;
}

function coursera_theme($existing, $type, $theme, $path){
    return array(
            'courses_list_data'=>array(
                'template'=>'course-list-data',
                'path'=>$path.'/templates',
                'type'=>'theme',
                'variables' => array(
                    'coursesListArray' => NULL,                      
                ),
            ),  
            'courses_output_html'=>array(
                'template'=>'courses-output-html',
                'path'=>$path.'/templates',
                'type'=>'theme',
                'variables' => array(
                    'courseListHtml' => NULL,                      
                    'searchCourseFormHtml' => NULL,                      
                ),
            ),              
            'search_course_form'=>array(
            'template'=>'search-course-form',
            'path'=>$path.'/templates',
            'type'=>'theme',
            'variables' => array(
                'courseType' => NULL,
                'languages' => NULL,
                'certificates' => NULL,
                'categories' => NULL,
                'partnerIds' => NULL,
            ),
           ),      
            'course_detail_page'=>array(
            'template'=>'course-detail-page',
            'path'=>$path.'/templates',
            'type'=>'theme',
            'variables' => array(
                'elements' => NULL,
                'linked' => NULL,
                'languages' => NULL,
                'certificates' => NULL,
                'categories' => NULL,
                'partnerIds' => NULL,
            ),
        ),
    );
}

/*
 * Code Refernce 
 * URL : http://php.net/manual/en/function.sort.php 
 */
function array_sort($array, $on, $order=SORT_ASC){
    $new_array = array();
    $sortable_array = array();
    if (count($array) > 0) {
        foreach ($array as $k => $v) {
            if (is_array($v)) {
                foreach ($v as $k2 => $v2) {
                    if ($k2 == $on) {
                        $sortable_array[$k] = $v2;
                    }
                }
            } else {
                $sortable_array[$k] = $v;
            }
        }

        switch ($order) {
            case SORT_ASC:
                asort($sortable_array);
            break;
            case SORT_DESC:
                arsort($sortable_array);
            break;
        }

        foreach ($sortable_array as $k => $v) {
            $new_array[$k] = $array[$k];
        }
    }

    return $new_array;
}
?>